### ISSUE TITLE
Kindergartens are shown twice

### ISSUE THREAD

**Issue by UJehle** [EPajares/goat#115]
If kindergartens are inserted in OSM as buildings + land use, GOAT will display two kindergarten symbols, although there is actually only one kindergarten (building + associated area). 

Screenshot of how it looks in OSM:
<img width="913" alt="Kindergarten landuse + building_OSM" src="https://user-images.githubusercontent.com/49870195/60896774-34a3ec00-a267-11e9-8646-852d48f26b6e.PNG">

Screenshot of how it looks in GOAT:
<img width="418" alt="Kindergarten landuse + building_GOAT" src="https://user-images.githubusercontent.com/49870195/60896773-34a3ec00-a267-11e9-91a2-8aea0c865a66.PNG">
(this example shows the "Gemeindekindergarten" in Langenbach)

Solution idea: No symbol for the land use "Kindergarten" should be displayed if there is also a building "Kindergarten" in it.

**Comment by EPajares** [comment]
Thanks! This somehow a bug I would say. We should double check what is really causing this issue and then resolve it. At the following position in the codebase this issue is caused: https://github.com/EPajares/goat/blob/53c14b3a3340ac575177f9d9a7e6ed06f50552ca/app/data_preparation/SQL/pois.sql#L1-L75

I will open a new branch called Fix_double_counting_pois. This issue though has not the highest priority.

@MoritzSGit could you kindly handle this issue.

**Comment by EPajares** [comment]
We do have an additional issue with the schools. For schools with the name Grund- und Hauptschule we only create a Pois for Hauptschule. In fact I think we would need two POIs although both schools are probably in the same building.

**Comment by EPajares** [comment]
We should consider #73

**Comment by MoritzSGit** [comment]
I propose a union of all overlapping kindergarten polygons. This way, a kindergarten building within a kindergarten parcel will count as one object.

In a second step, the kindergarten points will be considered. They will only be added to the pois list if they are not within a kindergarten polygon.
